version: '2'
volumes:
        unifi-data:
        nginx-data:
        letsencrypt:
        db:
services:
        mongo:
                build: ./mongo
                volumes:
                       - db:/data/db
        ddclient:
                build: ./ddclient-cloudflare
                privileged: true
        nginx:
                build: ./nginx
                privileged: true
                ports:
                        - "443:443"
                volumes:
                        - "nginx-data:/app/data"
                        - "letsencrypt:/etc/letsencrypt"

                links:
                        - "unifi"
        unifi:
                build: ./unifi
                ports:
                        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
                        - "10001:10001/udp" # AP discovery 
                        - "3478:3478/udp" # STUN
                        - "6789:6789/tcp" # Mobile speed tests
                        - "8080:8080/tcp" # Device controller communication
                        - "8880:8880/tcp" # HTTP portal redirection
                        - "8843:8843/tcp" # HTTPS portal redirection
                volumes:
                        - "unifi-data:/unifi"
